# RSX utility script to convert shader source files into C strings
# Because doing it manually is really boring

import sys
import os

def strip_comments_from_line(line: str):
    try:
        comment_idx = line.index("//")

        return line[:comment_idx]
    except ValueError:
        return line


def process_directory(directory_path, output_file, strip_comments=False):

    for root, dirs, files in os.walk(directory_path):
        for filename in files:

            # wowzers output_file and file_output we really cookin with these variable names
            file_output = process_file(os.path.join(root, filename), output_file, strip_comments, True)

            output_file.write(f"// File: {filename}\n")
            output_file.write(file_output)

def process_file(file_path, output_file, strip_comments=False, return_str=False):

    file_output = ""

    filename = os.path.basename(file_path).split(".")[0]

    file_output += "constexpr static const char " + filename + "_shader_src[] = {\n"

    with open(file_path, "r") as f:

        all_lines = f.readlines()

        i = 0
        for line in all_lines:

            # if the line defines the src symbol, replace the current file output with the symbol name
            if line.startswith("// SRC Symbol Name:"):

                # skip prefix
                line = line[19:].strip()

                file_output = "constexpr static const char " + line + "[] = {\n"
                continue

            if strip_comments: line = strip_comments_from_line(line)

            line = line.strip()

            if len(line) == 0:
                continue

            file_output += f"\"{line}\\n\""

            file_output += ";" if i == len(all_lines)-1 else "\n"

            i += 1

    file_output += "};\n\n"

    if return_str:
        return file_output
    else:
        output_file.write(file_output)

if __name__ == "__main__":
    # script name, input path, output path, strip comments
    assert len(sys.argv) >= 3

    input_path = sys.argv[1]
    output_path = sys.argv[2]
    strip_comments = True if (len(sys.argv) > 3 and sys.argv[3] == "1") else False

    output_file = open(output_path, "w")

    output_file.write("// File auto-generated by RSX script shaderstr.py\n")
    if strip_comments: output_file.write("// Comments have been automatically stripped\n")
    if os.path.isdir(input_path):
        process_directory(input_path, output_file, strip_comments)
    else:
        process_file(input_path, output_file, strip_comments, False)

    output_file.close()